esphome:
  name: esp32-audio-kit

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "esp32audio_hotspot"
  #   password: "esp32audio_pass"
# captive_portal:

i2c:
  sda: GPIO33
  scl: GPIO32
  # frequency: 400kHz
  # scan: true

external_components:
  - source: github://pr#3552
    components: [es8388]
    refresh: 0s

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO27
  i2s_mclk_pin: GPIO0
  
microphone:
  - platform: i2s_audio
    id: i2smic
    i2s_din_pin: GPIO35
    adc_type: external
    pdm: false

es8388:

media_player:
  - platform: i2s_audio
    id: i2smedia
    name: "ESP32 Audio Kit"
    i2s_dout_pin: GPIO26
    dac_type: external
    mode: stereo

voice_assistant:
  microphone: i2smic
  media_player: i2smedia
  on_listening:
    - light.turn_on:
        id: red_led
  on_start:
    - light.turn_off:
        id: red_led
  on_stt_end:
    - light.turn_off:
        id: red_led
    - text_sensor.template.publish:
        id: last_stt
        state: !lambda 'return x;'
  on_stt_vad_start:
    - light.turn_off:
        id: red_led
    - homeassistant.service:
        service: input_text.set_value
        data:
          value: media_player.voice_box_player
          entity_id: input_text.last_voice_box_triggered
  on_tts_start:
    - light.turn_off:
        id: red_led
    - text_sensor.template.publish:
        id: last_tts
        state: !lambda 'return x;'
    - homeassistant.service:
        service: script.esphome_notify
        data:
          target: media_player.voice_box_player
        data_template:
          message: "{{ msg }}"
        variables:
          msg: return x;

switch:
  - platform: gpio
    pin: GPIO21
    name: "AMP Switch"
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
      mode:
        input: true
    name: "Jack Status"

  - platform: gpio
    pin: 
      number: GPIO36
      inverted: true
    name: "Key 1"
    filters:
      - delayed_off: 10ms
    on_click:
      - if:
          condition: voice_assistant.is_running
          then:
            - voice_assistant.stop:
            - light.turn_off:
                id: red_led
          else:
            - voice_assistant.start_continuous:

  - platform: gpio
    pin:
      number: GPIO013
      inverted: true
    name: "Key 2"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO19
      inverted: true
    name: "Key 3"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO23
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 4"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO018
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 5"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin: 
      number: GPIO5
      mode: input_pullup
      inverted: true
    name: "Key 6"
    filters:
      - delayed_off: 10ms
    on_press:
      - light.turn_on:
          id: red_led
      - voice_assistant.start:
          silence_detection: true
    on_release:
      - light.turn_off:
          id: red_led
      - voice_assistant.stop:
  - platform: gpio
    pin: 
       number: GPIO34
       inverted: true
    name: "SDCard Sense"
    filters:
      - delayed_off: 50ms
      - delayed_on: 50ms

output:
  - platform: ledc
    pin: 
      number: GPIO22
      inverted: true
    id: output_led

light:
  - platform: binary
    name: "Red LED"
    id: red_led
    output: output_led
    restore_mode: ALWAYS_OFF

text_sensor:
  - platform: template
    name: "Last STT"
    id: last_stt
    entity_category: diagnostic
    update_interval: never

  - platform: template
    name: "Last TTS"
    id: last_tts
    entity_category: diagnostic
    update_interval: never